use std::fs;
use std::path::Path;

use crate::conformance::{
    inspect_icon, IconInspection, ICON_SPEC, MANIFEST_PATH, MAX_ICON_BYTES, REPORT_PATH,
};
use crate::model::{IconConformanceReport, IconConformanceStatus};

pub fn write_icon_conformance_report(project_path: &Path) -> Result<IconConformanceReport, String> {
    let root = project_path
        .canonicalize()
        .map_err(|error| format!("Cannot open project: {error}"))?;
    if !root.is_dir() {
        return Err("Project path is not a directory".to_string());
    }

    let inspection = inspect_icon(&root);
    let report_path = root.join(REPORT_PATH);
    let parent = report_path
        .parent()
        .ok_or_else(|| "Cannot determine report directory".to_string())?;
    fs::create_dir_all(parent)
        .map_err(|error| format!("Cannot create report directory: {error}"))?;
    fs::write(&report_path, render_icon_report(&root, &inspection))
        .map_err(|error| format!("Cannot write icon conformance report: {error}"))?;

    Ok(IconConformanceReport {
        path: REPORT_PATH.to_string(),
        status: inspection.conformance.status,
    })
}

fn render_icon_report(root: &Path, inspection: &IconInspection) -> String {
    let status = match inspection.conformance.status {
        IconConformanceStatus::Compliant => "compliant",
        IconConformanceStatus::Legacy => "legacy",
        IconConformanceStatus::Missing => "missing",
        IconConformanceStatus::Invalid => "invalid",
    };
    let declared_icon = inspection
        .conformance
        .declared_icon
        .as_deref()
        .unwrap_or("(not declared)");
    let resolved_icon = inspection
        .conformance
        .resolved_icon
        .as_deref()
        .unwrap_or("(none)");

    let mut report = format!(
        "# Atrium icon conformance\n\n- Specification: `{ICON_SPEC}`\n- Project: `{}`\n- Status: `{status}`\n- Manifest: `{MANIFEST_PATH}`\n- Declared icon: `{declared_icon}`\n- Resolved icon: `{resolved_icon}`\n\n## Rules\n- `schema` must be `1`.\n- `identity.icon` must be a relative path inside the project.\n- The icon must be tracked source material, not a generated build artifact.\n- Accepted formats: PNG, SVG, or WebP.\n- Maximum file size: {} KiB.\n\n## Findings\n",
        root.display(),
        MAX_ICON_BYTES / 1024
    );
    for finding in &inspection.findings {
        report.push_str(&format!("- {finding}\n"));
    }
    report.push_str("\n## Required action\n");
    for action in &inspection.actions {
        report.push_str(&format!("- {action}\n"));
    }
    report.push_str(
        "\nThis report was generated by Atrium. The project development Agent may use it to make the repository conform to the declared project protocol.\n",
    );
    report
}

#[cfg(test)]
mod tests {
    use super::write_icon_conformance_report;
    use crate::conformance::REPORT_PATH;
    use crate::model::IconConformanceStatus;
    use std::fs;

    fn temp_project(name: &str) -> std::path::PathBuf {
        let root = std::env::temp_dir().join(format!("atrium-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(&root).expect("create fixture project");
        root
    }

    #[test]
    fn writes_an_agent_facing_icon_report() {
        let root = temp_project("icon-report");
        let report = write_icon_conformance_report(&root).expect("write report");
        assert_eq!(report.path, REPORT_PATH);
        assert_eq!(report.status, IconConformanceStatus::Missing);
        assert!(root.join(REPORT_PATH).is_file());

        fs::remove_dir_all(root).expect("remove fixture project");
    }
}
