use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::model::GuidanceStatus;
use crate::project_path::{
    canonical_project_root, read_project_text_file, write_project_text_file,
};

pub const GUIDANCE_METADATA_PATH: &str = ".atrium/guidance.toml";
// This acknowledgement is maintained by the project development Agent after
// it applies the generated guidance. Atrium only reads it as structured state.
pub const GUIDANCE_SYNC_PATH: &str = ".atrium/guidance-sync.toml";
// Increment when the generated Agent instructions or their migration contract changes.
pub const GUIDANCE_REVISION: u32 = 3;
// Keep this aligned with the manifest schema supported by the scanner.
pub const GUIDANCE_PROTOCOL_SCHEMA: u32 = crate::manifest_schema::CURRENT_SCHEMA;

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct GuidanceMetadata {
    guidance_revision: u32,
    protocol_schema: u32,
}

pub fn inspect_guidance_status(project_path: &Path) -> GuidanceStatus {
    let metadata = read_guidance_metadata(project_path);
    let sync = read_guidance_sync(project_path);
    let metadata_is_current = metadata
        .as_ref()
        .map(|value| {
            value.guidance_revision == GUIDANCE_REVISION
                && value.protocol_schema == GUIDANCE_PROTOCOL_SCHEMA
        })
        .unwrap_or(false);
    let sync_is_current = sync
        .as_ref()
        .map(|value| {
            value.guidance_revision == GUIDANCE_REVISION
                && value.protocol_schema == GUIDANCE_PROTOCOL_SCHEMA
        })
        .unwrap_or(false);

    GuidanceStatus {
        revision: metadata.as_ref().map(|value| value.guidance_revision),
        needs_update: !metadata_is_current,
        needs_sync: !metadata_is_current || !sync_is_current,
    }
}

pub fn write_guidance_metadata(project_path: &Path) -> Result<String, String> {
    let root = canonical_project_root(project_path)?;
    let metadata = GuidanceMetadata {
        guidance_revision: GUIDANCE_REVISION,
        protocol_schema: GUIDANCE_PROTOCOL_SCHEMA,
    };
    let content = format!(
        "# Generated by Atrium. This file tracks the agent-facing guidance contract.\n\nguidance_revision = {}\nprotocol_schema = {}\n",
        metadata.guidance_revision, metadata.protocol_schema
    );
    write_project_text_file(&root, Path::new(GUIDANCE_METADATA_PATH), &content)
        .map_err(|error| format!("Cannot write guidance metadata: {error}"))?;
    Ok(GUIDANCE_METADATA_PATH.to_string())
}

fn read_guidance_metadata(project_path: &Path) -> Option<GuidanceMetadata> {
    let root = canonical_project_root(project_path).ok()?;
    let raw = read_project_text_file(&root, Path::new(GUIDANCE_METADATA_PATH)).ok()??;
    toml::from_str(&raw).ok()
}

fn read_guidance_sync(project_path: &Path) -> Option<GuidanceMetadata> {
    let root = canonical_project_root(project_path).ok()?;
    let raw = read_project_text_file(&root, Path::new(GUIDANCE_SYNC_PATH)).ok()??;
    toml::from_str(&raw).ok()
}

#[cfg(test)]
mod tests {
    use super::{
        inspect_guidance_status, write_guidance_metadata, GUIDANCE_METADATA_PATH,
        GUIDANCE_PROTOCOL_SCHEMA, GUIDANCE_REVISION, GUIDANCE_SYNC_PATH,
    };
    use std::fs;

    fn fixture_root(name: &str) -> std::path::PathBuf {
        let root =
            std::env::temp_dir().join(format!("atrium-guidance-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(&root).expect("create fixture project");
        root
    }

    #[test]
    fn missing_metadata_needs_an_update() {
        let root = fixture_root("missing");

        let status = inspect_guidance_status(&root);

        assert_eq!(status.revision, None);
        assert!(status.needs_update);
        assert!(status.needs_sync);
        fs::remove_dir_all(root).expect("remove fixture project");
    }

    #[test]
    fn current_metadata_is_up_to_date() {
        let root = fixture_root("current");
        write_guidance_metadata(&root).expect("write metadata");

        let status = inspect_guidance_status(&root);

        assert_eq!(status.revision, Some(GUIDANCE_REVISION));
        assert!(!status.needs_update);
        assert!(status.needs_sync);
        assert!(root.join(GUIDANCE_METADATA_PATH).is_file());
        fs::remove_dir_all(root).expect("remove fixture project");
    }

    #[test]
    fn current_metadata_needs_agent_acknowledgement() {
        let root = fixture_root("needs-ack");
        write_guidance_metadata(&root).expect("write metadata");

        let status = inspect_guidance_status(&root);

        assert!(!status.needs_update);
        assert!(status.needs_sync);
        fs::remove_dir_all(root).expect("remove fixture project");
    }

    #[test]
    fn current_metadata_and_agent_acknowledgement_are_synced() {
        let root = fixture_root("synced");
        write_guidance_metadata(&root).expect("write metadata");
        let path = root.join(GUIDANCE_SYNC_PATH);
        fs::create_dir_all(path.parent().expect("sync parent")).expect("create sync parent");
        fs::write(
            path,
            format!(
                "guidance_revision = {}\nprotocol_schema = {}\n",
                GUIDANCE_REVISION, GUIDANCE_PROTOCOL_SCHEMA
            ),
        )
        .expect("write sync acknowledgement");

        let status = inspect_guidance_status(&root);

        assert!(!status.needs_update);
        assert!(!status.needs_sync);
        fs::remove_dir_all(root).expect("remove fixture project");
    }

    #[test]
    fn stale_metadata_needs_an_update() {
        let root = fixture_root("stale");
        let path = root.join(GUIDANCE_METADATA_PATH);
        fs::create_dir_all(path.parent().expect("metadata parent"))
            .expect("create metadata parent");
        fs::write(
            path,
            format!(
                "guidance_revision = {}\nprotocol_schema = {}\n",
                GUIDANCE_REVISION.saturating_sub(1),
                GUIDANCE_PROTOCOL_SCHEMA
            ),
        )
        .expect("write stale metadata");

        let status = inspect_guidance_status(&root);

        assert_eq!(status.revision, Some(GUIDANCE_REVISION.saturating_sub(1)));
        assert!(status.needs_update);
        assert!(status.needs_sync);
        fs::remove_dir_all(root).expect("remove fixture project");
    }

    #[test]
    fn unknown_metadata_fields_need_an_update() {
        let root = fixture_root("unknown-field");
        let path = root.join(GUIDANCE_METADATA_PATH);
        fs::create_dir_all(path.parent().expect("metadata parent"))
            .expect("create metadata parent");
        fs::write(
            path,
            format!(
                "guidance_revision = {}\nprotocol_schema = {}\nfuture_field = true\n",
                GUIDANCE_REVISION, GUIDANCE_PROTOCOL_SCHEMA
            ),
        )
        .expect("write invalid metadata");

        let status = inspect_guidance_status(&root);

        assert_eq!(status.revision, None);
        assert!(status.needs_update);
        assert!(status.needs_sync);
        fs::remove_dir_all(root).expect("remove fixture project");
    }
}
