use std::fs;
use std::path::Path;

use crate::conformance::{
    inspect_icon, IconInspection, ICON_SPEC, MANIFEST_PATH, MAX_ICON_BYTES, REPORT_PATH,
};
use crate::model::{
    IconConformanceReport, IconConformanceStatus, ProjectConfigurationReport,
    ProjectConfigurationStatus, ProjectGuidanceReport, ProjectSnapshot,
};

pub const CONFIGURATION_REPORT_PATH: &str = ".atrium/reports/project-configuration.md";

pub fn write_icon_conformance_report(project_path: &Path) -> Result<IconConformanceReport, String> {
    let root = project_path
        .canonicalize()
        .map_err(|error| format!("Cannot open project: {error}"))?;
    if !root.is_dir() {
        return Err("Project path is not a directory".to_string());
    }

    let inspection = inspect_icon(&root);
    let report_path = root.join(REPORT_PATH);
    let parent = report_path
        .parent()
        .ok_or_else(|| "Cannot determine report directory".to_string())?;
    fs::create_dir_all(parent)
        .map_err(|error| format!("Cannot create report directory: {error}"))?;
    fs::write(&report_path, render_icon_report(&root, &inspection))
        .map_err(|error| format!("Cannot write icon conformance report: {error}"))?;

    Ok(IconConformanceReport {
        path: REPORT_PATH.to_string(),
        status: inspection.conformance.status,
    })
}

fn render_icon_report(root: &Path, inspection: &IconInspection) -> String {
    let status = match inspection.conformance.status {
        IconConformanceStatus::Compliant => "compliant",
        IconConformanceStatus::Legacy => "legacy",
        IconConformanceStatus::Missing => "missing",
        IconConformanceStatus::Invalid => "invalid",
    };
    let declared_icon = inspection
        .conformance
        .declared_icon
        .as_deref()
        .unwrap_or("(not declared)");
    let resolved_icon = inspection
        .conformance
        .resolved_icon
        .as_deref()
        .unwrap_or("(none)");

    let mut report = format!(
        "# Atrium icon conformance\n\n- Specification: `{ICON_SPEC}`\n- Project: `{}`\n- Status: `{status}`\n- Manifest: `{MANIFEST_PATH}`\n- Declared icon: `{declared_icon}`\n- Resolved icon: `{resolved_icon}`\n\n## Rules\n- `schema` must be `1`.\n- `identity.icon` must be a relative path inside the project.\n- The icon must be tracked source material, not a generated build artifact.\n- Accepted formats: PNG, SVG, or WebP.\n- Maximum file size: {} KiB.\n\n## Findings\n",
        root.display(),
        MAX_ICON_BYTES / 1024
    );
    for finding in &inspection.findings {
        report.push_str(&format!("- {finding}\n"));
    }
    report.push_str("\n## Required action\n");
    for action in &inspection.actions {
        report.push_str(&format!("- {action}\n"));
    }
    report.push_str(
        "\nThis report was generated by Atrium. The project development Agent may use it to make the repository conform to the declared project protocol.\n",
    );
    report
}

pub fn write_project_configuration_report(
    project_path: &Path,
    project: &ProjectSnapshot,
) -> Result<ProjectConfigurationReport, String> {
    let root = project_path
        .canonicalize()
        .map_err(|error| format!("Cannot open project: {error}"))?;
    if !root.is_dir() {
        return Err("Project path is not a directory".to_string());
    }
    let report_path = root.join(CONFIGURATION_REPORT_PATH);
    let parent = report_path
        .parent()
        .ok_or_else(|| "Cannot determine report directory".to_string())?;
    fs::create_dir_all(parent)
        .map_err(|error| format!("Cannot create report directory: {error}"))?;
    fs::write(&report_path, render_configuration_report(&root, project))
        .map_err(|error| format!("Cannot write project configuration report: {error}"))?;

    Ok(ProjectConfigurationReport {
        path: CONFIGURATION_REPORT_PATH.to_string(),
        status: project.configuration.status,
    })
}

pub fn write_project_guidance_reports(
    project_path: &Path,
    project: &ProjectSnapshot,
) -> Result<ProjectGuidanceReport, String> {
    let configuration_report = write_project_configuration_report(project_path, project)?;
    let icon_report = write_icon_conformance_report(project_path)?;

    Ok(ProjectGuidanceReport {
        paths: vec![configuration_report.path, icon_report.path],
        configuration_status: configuration_report.status,
        icon_status: icon_report.status,
    })
}

fn render_configuration_report(root: &Path, project: &ProjectSnapshot) -> String {
    let status = match &project.configuration.status {
        ProjectConfigurationStatus::Configured => "configured",
        ProjectConfigurationStatus::Missing => "missing",
        ProjectConfigurationStatus::Invalid => "invalid",
    };
    let mut report = format!(
        "# Atrium project configuration guidance\n\n- Project: `{}`\n- Status: `{status}`\n- Manifest: `{MANIFEST_PATH}`\n\n",
        root.display()
    );
    report.push_str(
        "Atrium reads platform, channel, and build-profile facts only from the structured manifest. This report is guidance for the project development Agent; Atrium never parses this Markdown file.\n\n",
    );
    report.push_str("## Required manifest shape\n\n```toml\nschema = 1\nprofile = \"<adapter-name>\"\n\n# Declare only platforms this project actually builds for.\n[[platforms]]\nid = \"<platform-id>\"\nlabel = \"<Platform label>\"\n\n# Declare the distribution channel for each supported build context.\n[[channels]]\nid = \"<channel-id>\"\nlabel = \"<Channel label>\"\n\n# Bind each platform/channel combination to existing repository commands.\n[[build_profiles]]\nid = \"<profile-id>\"\nlabel = \"<Platform> · <Channel>\"\nplatform = \"<platform-id>\"\nchannel = \"<channel-id>\"\n\n[build_profiles.commands]\nrun = \"<command-id-or-source>\"\ncheck = \"<command-id-or-source>\"\nbuild = \"<command-id-or-source>\"\n```\n\n");
    report.push_str("## Cleanup declarations\n\n");
    report.push_str(
        "Atrium cleans only directories explicitly declared by the project in the manifest. The project development Agent should add the cache and build output directories that are safe to regenerate:\n\n```toml\n[cleanup]\ncache = [\"<relative cache directory>\"]\nbuild = [\"<relative build directory>\"]\n```\n\n",
    );
    report.push_str("## Build artifact declarations\n\n");
    report.push_str(
        "Each build profile may declare files or directories it produces. Atrium only reports and opens these explicit paths; it does not infer artifacts from framework defaults:\n\n```toml\n[[build_profiles]]\n# ... profile fields ...\nartifacts = [\"<relative file or directory>\"]\n```\n\n",
    );
    report.push_str(
        "## Project tools and links\n\nThe optional `[tools]` section can name a terminal executable for this project. It is passed as a program path, never as a shell command. If it is absent or empty, Atrium uses the operating system's default terminal; users do not need to enter a command. Editor launchers are intentionally not part of the current protocol. Optional `[[links]]` entries are opened only after validating their declared URL scheme:\n\n```toml\n[tools]\nterminal = \"\"\n\n[[links]]\nid = \"preview\"\nlabel = \"Local preview\"\nurl = \"http://127.0.0.1:3000\"\nkind = \"preview\"\n```\n\n",
    );
    report.push_str("## Structured commands discovered by Atrium\n\n");
    if project.commands.is_empty() {
        report.push_str("- No supported repository command was discovered.\n");
    } else {
        for command in &project.commands {
            report.push_str(&format!(
                "- `{}` — `{}` (`{}`)\n",
                command.id, command.source, command.display_command
            ));
        }
    }
    report.push_str("\n## Current issues\n\n");
    if project.configuration.issues.is_empty() {
        report.push_str("- No configuration issue was reported.\n");
    } else {
        for issue in &project.configuration.issues {
            report.push_str(&format!("- {issue}\n"));
        }
    }
    report.push_str(
        "\nThe project development Agent should update `.atrium/manifest.toml` in the repository after verifying the native build scripts. Do not invent a new build command in Atrium.\n",
    );
    report
}

#[cfg(test)]
mod tests {
    use super::write_icon_conformance_report;
    use crate::conformance::REPORT_PATH;
    use crate::model::IconConformanceStatus;
    use std::fs;

    fn temp_project(name: &str) -> std::path::PathBuf {
        let root = std::env::temp_dir().join(format!("atrium-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(&root).expect("create fixture project");
        root
    }

    #[test]
    fn writes_an_agent_facing_icon_report() {
        let root = temp_project("icon-report");
        let report = write_icon_conformance_report(&root).expect("write report");
        assert_eq!(report.path, REPORT_PATH);
        assert_eq!(report.status, IconConformanceStatus::Missing);
        assert!(root.join(REPORT_PATH).is_file());

        fs::remove_dir_all(root).expect("remove fixture project");
    }
}
